name: Github actions con variables
on: # cuando ejecutar

  push:
    branches: [ ibs ]

  workflow_dispatch:
      inputs:
        Variable1:
          description: 'Descripcion var1'
          required: true
          default: 'valordefault'

jobs:
  test_job:
    runs-on: ubuntu-latest # utilizar una versión concreta
    
    steps: 
      - name: "Primera prueba"
        env:
          INPUT_VAR1: ${{ github.event.inputs.Variable1 }}
        run: echo "$INPUT_VAR1"