name: Github actions con variables
on: # cuando ejecutar

  workflow_dispatch:
      inputs:
        Variable1:
          description: 'Descripcion var1'
          required: true
          default: 'valordefault'
        Variable2:
            description: 'Descripcion var2'
            required: true
            default: 'development'  
            type: choice
            options:
            - development
            - staging
            - production    

jobs:
  test_job:
    runs-on: ubuntu-latest # utilizar una versión concreta

    steps:
      - name: "Primera variable"
        run: |
          echo "Variable 1: ${{ github.event.inputs.Variable1 }}"
          echo "Variable 2: ${{ github.event.inputs.Variable2 }}"